package com.clearent.device.config.domain;

public enum ClearentConfigCodes {

    TERMINAL_MAJOR_5C_FAILED,
    EMV_CONFIGURATION_SUCCESS,
    MAJOR_TAGS_RETRIEVE_FAILED,
    CONTACT_MAJOR_TAGS_UPDATE_FAILED,
    CALL_FAILED,
    JSON_SERIALIZATION_FAILED,
    NO_PAYLOAD,
    NO_MOBILE_DEVICE,
    CONTACT_FAILED,
    CONTACT_CAPKS_FAILED
}
